In [20]:
import csv
from matplotlib import pyplot as plt
from pathlib import Path
import pandas as pd

def readSolution(folder_name):
    
    folder = Path(folder_name)

    sols = {}
    
    for csv_file in folder.glob("*.csv"):
        with open(csv_file) as f:
            reader = csv.DictReader(f, delimiter=";")
        
            for row in reader:
                instanceId = row["instanceId"]
                validSolution = row["validSolution"]
                numOfPlates = row["nPlates"]
                totalGeoLoss = row["totalGeoLoss"]
                widthResidual = row["widthResidual"]

                sols[instanceId] = {"validSolution" : validSolution, 
                                    "numOfPlates" : int(numOfPlates), 
                                    "totalGeoLoss": totalGeoLoss, 
                                    "widthResidual": int(widthResidual)}
    

    return sols

rotatedSols = readSolution("rotation")
decrAreaSols = readSolution("decreasingorder")
basicSols = readSolution("basic")
incrAreaSols = readSolution("increasingorder")
evaluateSols = readSolution("evaluate")


solutions = {
    "basic": basicSols,
    "rotation": rotatedSols,
    "decreasing order": decrAreaSols,
    "evaluate": evaluateSols
}

metrics = [
    "validSolution",
    "numOfPlates",
    "totalGeoLoss",
    "widthResidual"
]

tables = {}

for metric in metrics:
    tables[metric] = pd.DataFrame({
        algorithm: {
            instanceId: values[metric]
            for instanceId, values in sols.items()
        }
        for algorithm, sols in solutions.items()
    })

    tables[metric].index.name = "instanceId"

tables["numOfPlates"]

            basic  rotation  decreasing order  evaluate
instanceId
A10             6         6                 5         5
A11             6         5                 5         5
A12             4         3                 2         3
A13            15        14                14        14
A14            19        17                15        14
A15            22        18                16        15
A16             3         3                 3         3
A17             3         2                 2         2
A18             6         6                 6         4
A19             5         4                 3         3
A1              1         1                 1         1
A20             2         2                 2         2
A2              8         6                 6         6
A3              4         4                 3         3
A4              4         4                 3         3
A5              7         5                 4         4
A6              4         4                 4         3
A7              7         6                 5         5
A8             13        11                10         9
A9              4         4                 4         4
B10            27        26                24        22
B11            30        27                23        22
B12            22        19                18        16
B13            39        35                32        30
B14            14        13                12        11
B15            35        33                29        27
B1              7         6                 5         5
B2             25        23                20        19
B3             30        28                23        22
B4             12        11                10        10
B5             32        28                28        26
B6             15        14                13        13
B7             14        13                12        11
B8             28        24                22        21
B9             23        21                19        18

In [18]:
tables["totalGeoLoss"]

               basic  rotation decreasingorder  evaluate
instanceId
A10              38%     34.5%             24%       23%
A11         40.6667%       32%           25.6%     18.4%
A12              60%       46%           22.5%       42%
A13         24.5333%  20.0714%        18.7857%  18.2143%
A14         35.8947%  29.4706%        19.8667%  14.7143%
A15         41.9545%  30.3333%          21.75%  16.5333%
A16         26.3333%  27.3333%        27.6667%       30%
A17         61.3333%       48%             48%     46.5%
A18         44.6667%  44.1667%        45.8333%     20.5%
A19            50.4%       42%        26.3333%       22%
A1               52%       42%             42%       42%
A20              55%       47%           46.5%     46.5%
A2           48.375%       26%        30.1667%  30.1667%
A3            40.25%     41.5%        23.6667%  18.3333%
A4            40.25%     41.5%        25.3333%  24.6667%
A5          54.4286%     36.6%          24.75%     19.5%
A6            38.25%       37%           38.5%       24%
A7               39%       37%             26%     25.8%
A8          42.6154%  30.6364%           24.6%  19.3333%
A9            37.75%    39.25%           38.5%    37.25%
B10         30.7778%  29.4615%         24.625%  17.8182%
B11         40.8667%  33.7407%        22.3913%  19.6818%
B12         37.5909%  27.5789%        22.7778%  15.0625%
B13         34.6154%  26.8857%        19.9062%       15%
B14         33.7857%  27.2308%          21.25%  13.7273%
B15         34.5143%  29.7576%        21.6207%  15.7407%
B1          39.7143%  30.6667%           18.2%     15.8%
B2             33.4%   28.087%           16.5%  13.3158%
B3          38.4333%       34%             19%  16.4091%
B4          35.4167%  27.1818%           21.7%     18.7%
B5          46.8125%     39.5%           39.5%  33.7692%
B6          32.1333%  25.7143%        21.7692%  20.9231%
B7          28.3571%  22.3846%        15.8333%  9.72727%
B8          36.6071%   25.125%        19.2727%  14.9048%
B9           31.913%  26.0952%        18.6842%  14.2778%