In [1]:
import csv
from matplotlib import pyplot as plt
from pathlib import Path
import pandas as pd

def readSolution(folder_name):
    
    folder = Path(folder_name)

    sols = {}
    
    for csv_file in folder.glob("*.csv"):
        with open(csv_file) as f:
            reader = csv.DictReader(f, delimiter=";")
        
            for row in reader:
                instanceId = row["instanceId"]
                validSolution = row["validSolution"]
                numOfPlates = row["nPlates"]
                totalGeoLoss = row["totalGeoLoss"]
                widthResidual = row["widthResidual"]

                sols[instanceId] = {"validSolution" : validSolution, 
                                    "numOfPlates" : int(numOfPlates), 
                                    "totalGeoLoss": totalGeoLoss, 
                                    "widthResidual": int(widthResidual)}
    

    return sols

rotatedSols = readSolution("rotation")
decrAreaSols = readSolution("decreasingorder")
basicSols = readSolution("basic")
incrAreaSols = readSolution("increasingorder")
evaluateSols = readSolution("evaluate")
evaluate2Sols = readSolution("evaluate_2")
HamzaSol = readSolution("Hamza")
HamzaSol2 = readSolution("Hamza_2")
winner = readSolution("winner")


solutions = {
    "Hamza" : HamzaSol,
    "Hamza 2" : HamzaSol2,
    "basic": basicSols,
    "rotation": rotatedSols,
    "decreasing order": decrAreaSols,
    "evaluate": evaluateSols,
    "evaluate 2": evaluate2Sols,
    "winner": winner
}

metrics = [
    "validSolution",
    "numOfPlates",
    "totalGeoLoss",
    "widthResidual"
]

tables = {}

for metric in metrics:
    tables[metric] = pd.DataFrame({
        algorithm: {
            instanceId: values[metric]
            for instanceId, values in sols.items()
        }
        for algorithm, sols in solutions.items()
    })

    tables[metric].index.name = "instanceId"

tables["numOfPlates"]

,Hamza,Hamza 2,basic,rotation,decreasing order,evaluate,evaluate 2,winner
instanceId,,,,,,,,
A1,1.0,1.0,1,1,1,1,1,1
A2,11.0,10.0,8,6,6,6,6,5
A3,5.0,4.0,4,4,3,3,3,3
A4,5.0,4.0,4,4,3,3,3,3
A5,6.0,6.0,7,5,4,4,4,4
A6,5.0,5.0,4,4,4,3,3,3
A7,8.0,8.0,7,6,5,5,5,4
A8,15.0,15.0,13,11,10,9,9,8
A9,6.0,6.0,4,4,4,4,3,3
A10,8.0,7.0,6,6,5,5,5,4
A11,9.0,7.0,6,5,5,5,5,4
A12,4.0,3.0,4,3,2,3,2,2
A13,25.0,21.0,15,14,14,14,13,12
A14,26.0,22.0,19,17,15,14,14,13
A15,27.0,24.0,22,18,16,15,15,13
A16,5.0,4.0,3,3,3,3,3,3
A17,3.0,3.0,3,2,2,2,2,2
A18,8.0,7.0,6,6,6,4,4,4
A19,5.0,5.0,5,4,3,3,3,3
A20,2.0,2.0,2,2,2,2,2,1
B10,NaN,NaN,27,26,24,22,22,20
B11,NaN,NaN,30,27,23,22,21,19
B12,NaN,NaN,22,19,18,16,16,15
B13,NaN,NaN,39,35,32,30,30,27
B14,NaN,NaN,14,13,12,11,11,10
B15,NaN,NaN,35,33,29,27,27,24
B1,NaN,NaN,7,6,5,5,5,5
B2,NaN,NaN,25,23,20,19,19,17
B3,NaN,NaN,30,28,23,22,22,19
B4,NaN,NaN,12,11,10,10,10,9
B5,NaN,NaN,32,28,28,26,26,21
B6,NaN,NaN,15,14,13,13,12,11
B7,NaN,NaN,14,13,12,11,11,11
B8,NaN,NaN,28,24,22,21,20,19
B9,NaN,NaN,23,21,19,18,18,17

In [3]:
tables["totalGeoLoss"]

,Hamza,basic,rotation,decreasing order,evaluate,evaluate 2,order eval 1,winner
instanceId,,,,,,,,
A1,74%,52%,42%,42%,42%,42%,48%,8%
A2,62.6364%,48.375%,26%,30.1667%,30.1667%,31.3333%,48.25%,6.6%
A3,55.4%,40.25%,41.5%,23.6667%,18.3333%,26.3333%,41%,5.33333%
A4,55.2%,40.25%,41.5%,25.3333%,24.6667%,22.6667%,21%,6.33333%
A5,50%,54.4286%,36.6%,24.75%,19.5%,16.5%,22.25%,5%
A6,54.2%,38.25%,37%,38.5%,24%,21%,37%,7.66667%
A7,53.875%,39%,37%,26%,25.8%,18.2%,29.3333%,4.75%
A8,51.6667%,42.6154%,30.6364%,24.6%,19.3333%,18.4444%,24.2%,5.5%
A9,60.5%,37.75%,39.25%,38.5%,37.25%,21.3333%,33.5%,5.33333%
A10,53.125%,38%,34.5%,24%,23%,23.2%,30.3333%,5%
A11,62.2222%,40.6667%,32%,25.6%,18.4%,28%,28.4%,5.75%
A12,61.25%,60%,46%,22.5%,42%,22.5%,46.3333%,5.5%
A13,55.08%,24.5333%,20.0714%,18.7857%,18.2143%,12.3077%,24.4667%,4%
A14,54.1923%,35.8947%,29.4706%,19.8667%,14.7143%,15.1429%,20.7333%,4.07692%
A15,53.5556%,41.9545%,30.3333%,21.75%,16.5333%,15.9333%,24.0588%,3.84615%
A16,60.4%,26.3333%,27.3333%,27.6667%,30%,30%,34.3333%,9.66667%
A17,65.3333%,61.3333%,48%,48%,46.5%,40.5%,37%,14.5%
A18,60.125%,44.6667%,44.1667%,45.8333%,20.5%,20.75%,32.4%,7.25%
A19,56.2%,50.4%,42%,26.3333%,22%,22.3333%,26%,7.66667%
A20,60%,55%,47%,46.5%,46.5%,56.5%,41.5%,9%
B10,NaN,30.7778%,29.4615%,24.625%,17.8182%,16.5%,32.1481%,5.55%
B11,NaN,40.8667%,33.7407%,22.3913%,19.6818%,14.619%,21.6522%,5.26316%
B12,NaN,37.5909%,27.5789%,22.7778%,15.0625%,14.9375%,21.9444%,4.66667%
B13,NaN,34.6154%,26.8857%,19.9062%,15%,14.1667%,22.2121%,4.11111%
B14,NaN,33.7857%,27.2308%,21.25%,13.7273%,13.2727%,22.6667%,3.8%
B15,NaN,34.5143%,29.7576%,21.6207%,15.7407%,14.4444%,26.6129%,4.5%
B1,NaN,39.7143%,30.6667%,18.2%,15.8%,14%,28.8333%,4.2%
B2,NaN,33.4%,28.087%,16.5%,13.3158%,12.9474%,20.1905%,3.23529%
B3,NaN,38.4333%,34%,19%,16.4091%,15.5909%,23.625%,3.78947%
B4,NaN,35.4167%,27.1818%,21.7%,18.7%,19%,22.1%,4.55556%
B5,NaN,46.8125%,39.5%,39.5%,33.7692%,33.7692%,38.2857%,18.1429%
B6,NaN,32.1333%,25.7143%,21.7692%,20.9231%,15.9167%,25%,4.90909%
B7,NaN,28.3571%,22.3846%,15.8333%,9.72727%,8.63636%,16.5%,4.63636%
B8,NaN,36.6071%,25.125%,19.2727%,14.9048%,11.2%,32.1481%,3.84211%
B9,NaN,31.913%,26.0952%,18.6842%,14.2778%,14.8333%,26.1429%,5.58824%